### ISSUE TITLE
Please update guzzlehttp/guzzle version into latest version

### ISSUE THREAD

**Issue by codepoetryindia** [mremi/UrlShortener#27]
I am facing versioning issues when I use other packages with it.

  Problem 1
    - Installation request for mremi/url-shortener ^2.3 -> satisfiable by mremi/url-shortener[v2.3.0].
    - mremi/url-shortener v2.3.0 requires guzzlehttp/guzzle ^6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.x-dev] but these conflict with your requirements or minimum-stability.

**Comment by mcaskill** [comment]
What version of guzzlehttp/guzzle is installed, or do you need?
