### ISSUE TITLE
Google broken

### ISSUE THREAD

**Issue by claygorman** [mremi/UrlShortener#8]
I cloned the project and tried to shorten with google url and it always returns null.

Command line works ok..

Would you mind testing?

**Comment by racibaz** [comment]
#9

**Comment by mremi** [comment]
Hi,

No need to return something, the given link is altered, it's an object, so a reference, so you can retrieve the shorten URL in your code with `$link->getShortUrl()`.

**Comment by racibaz** [comment]
@mremi  Thank you.
